"""Per-device conversation list, backing the sidebar's ChatGPT/Claude-style
"past conversations" list. There's no login, so `device_id` is an anonymous id
the frontend keeps in its URL (see frontend.py) - it scopes the list to one
browser/bookmarked link, not a real account.

Titles are generated by a cheap Haiku call the first time a thread gets a real
answer, in a background thread so it never adds latency to the response.
Everything here is best-effort: a failure here must never break /chat.
"""
import logging
import os
import threading

import psycopg
from pydantic import BaseModel, Field

from .llm import fast_llm

logger = logging.getLogger("threads")

DATABASE_URL = os.getenv("DATABASE_URL")

_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS threads (
    thread_id  TEXT PRIMARY KEY,
    device_id  TEXT NOT NULL,
    title      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_INDEX_SQL = "CREATE INDEX IF NOT EXISTS threads_device_idx ON threads (device_id, updated_at DESC)"


def setup():
    if not DATABASE_URL:
        return
    with psycopg.connect(DATABASE_URL, autocommit=True, connect_timeout=5) as conn:
        conn.execute(_TABLE_SQL)
        conn.execute(_INDEX_SQL)


class _Title(BaseModel):
    title: str = Field(
        description="A short 3-6 word title for this conversation, the way a "
        "chat app names a thread from its first exchange. No quotes, no "
        "trailing punctuation."
    )


_titler = fast_llm.with_structured_output(_Title)


def _generate_title(thread_id, question, answer):
    try:
        title = _titler.invoke(f"Question: {question}\nAnswer: {answer[:400]}").title.strip()[:80]
        if title:
            with psycopg.connect(DATABASE_URL, autocommit=True, connect_timeout=5) as conn:
                conn.execute(
                    "UPDATE threads SET title = %s WHERE thread_id = %s AND title IS NULL",
                    (title, thread_id),
                )
    except Exception:
        logger.warning("title generation failed for thread %s", thread_id, exc_info=True)


def touch(device_id, thread_id, question, answer):
    """Record activity on a thread (creating its row on the first real answer)
    and kick off background title generation the first time. Never raises."""
    if not DATABASE_URL or not device_id or not thread_id:
        return
    try:
        with psycopg.connect(DATABASE_URL, autocommit=True, connect_timeout=5) as conn:
            row = conn.execute(
                """INSERT INTO threads (thread_id, device_id)
                   VALUES (%s, %s)
                   ON CONFLICT (thread_id) DO UPDATE SET updated_at = now()
                   RETURNING title""",
                (thread_id, device_id),
            ).fetchone()
        if row is not None and row[0] is None:
            threading.Thread(
                target=_generate_title, args=(thread_id, question, answer), daemon=True
            ).start()
    except Exception:
        logger.warning("thread touch failed for %s", thread_id, exc_info=True)


def list_for_device(device_id, limit=30):
    if not DATABASE_URL or not device_id:
        return []
    try:
        with psycopg.connect(DATABASE_URL, autocommit=True, connect_timeout=5) as conn:
            rows = conn.execute(
                """SELECT thread_id, title, updated_at FROM threads
                   WHERE device_id = %s ORDER BY updated_at DESC LIMIT %s""",
                (device_id, limit),
            ).fetchall()
        return [{"thread_id": r[0], "title": r[1], "updated_at": r[2].isoformat()} for r in rows]
    except Exception:
        logger.warning("thread list failed for device %s", device_id, exc_info=True)
        return []
