"""Per-user conversation list, backing the sidebar's ChatGPT/Claude-style
"past conversations" list. `user_id` is the verified Google account id from
src/auth.py (the JWT's `sub` claim) - not client-supplied, so one user can't
list or read another's threads by guessing an id.

Titles are generated by a cheap Haiku call the first time a thread gets a real
answer, in a background thread so it never adds latency to the response.
Everything here is best-effort: a failure here must never break /chat.
"""
import logging
import os
import threading

import psycopg
from pydantic import BaseModel, Field

from .llm import fast_llm

logger = logging.getLogger("threads")

DATABASE_URL = os.getenv("DATABASE_URL")

_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS threads (
    thread_id  TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL,
    title      TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
)
"""
_INDEX_SQL = "CREATE INDEX IF NOT EXISTS threads_user_idx ON threads (user_id, updated_at DESC)"
# one-time rename from the pre-auth anonymous-device_id schema, if present -
# CREATE TABLE IF NOT EXISTS above is a no-op on an existing table, so this
# is what actually carries old installs over to the new column name.
_MIGRATE_SQL = """
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name = 'threads' AND column_name = 'device_id')
       AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                        WHERE table_name = 'threads' AND column_name = 'user_id')
    THEN
        ALTER TABLE threads RENAME COLUMN device_id TO user_id;
    END IF;
END $$
"""


def setup():
    if not DATABASE_URL:
        return
    with psycopg.connect(DATABASE_URL, autocommit=True, connect_timeout=5) as conn:
        conn.execute(_TABLE_SQL)
        conn.execute(_MIGRATE_SQL)
        conn.execute(_INDEX_SQL)


class _Title(BaseModel):
    title: str = Field(
        description="A short 3-6 word title for this conversation, the way a "
        "chat app names a thread from its first exchange. No quotes, no "
        "trailing punctuation."
    )


_titler = fast_llm.with_structured_output(_Title)


def _generate_title(thread_id, question, answer):
    try:
        title = _titler.invoke(f"Question: {question}\nAnswer: {answer[:400]}").title.strip()[:80]
        if title:
            with psycopg.connect(DATABASE_URL, autocommit=True, connect_timeout=5) as conn:
                conn.execute(
                    "UPDATE threads SET title = %s WHERE thread_id = %s AND title IS NULL",
                    (title, thread_id),
                )
    except Exception:
        logger.warning("title generation failed for thread %s", thread_id, exc_info=True)


def touch(user_id, thread_id, question, answer):
    """Record activity on a thread (creating its row on the first real answer)
    and kick off background title generation the first time. Never raises."""
    if not DATABASE_URL or not user_id or not thread_id:
        return
    try:
        with psycopg.connect(DATABASE_URL, autocommit=True, connect_timeout=5) as conn:
            row = conn.execute(
                """INSERT INTO threads (thread_id, user_id)
                   VALUES (%s, %s)
                   ON CONFLICT (thread_id) DO UPDATE SET updated_at = now()
                   RETURNING title""",
                (thread_id, user_id),
            ).fetchone()
        if row is not None and row[0] is None:
            threading.Thread(
                target=_generate_title, args=(thread_id, question, answer), daemon=True
            ).start()
    except Exception:
        logger.warning("thread touch failed for %s", thread_id, exc_info=True)


def list_for_user(user_id, limit=30):
    if not DATABASE_URL or not user_id:
        return []
    try:
        with psycopg.connect(DATABASE_URL, autocommit=True, connect_timeout=5) as conn:
            rows = conn.execute(
                """SELECT thread_id, title, updated_at FROM threads
                   WHERE user_id = %s ORDER BY updated_at DESC LIMIT %s""",
                (user_id, limit),
            ).fetchall()
        return [{"thread_id": r[0], "title": r[1], "updated_at": r[2].isoformat()} for r in rows]
    except Exception:
        logger.warning("thread list failed for user %s", user_id, exc_info=True)
        return []


def owner_of(thread_id):
    """None if the thread has no row yet (a brand-new conversation - allowed)
    or on any DB error (fail open here; /chat's own auth already required a
    verified user, this is just a defense-in-depth check on /history)."""
    if not DATABASE_URL or not thread_id:
        return None
    try:
        with psycopg.connect(DATABASE_URL, autocommit=True, connect_timeout=5) as conn:
            row = conn.execute(
                "SELECT user_id FROM threads WHERE thread_id = %s", (thread_id,)
            ).fetchone()
        return row[0] if row else None
    except Exception:
        logger.warning("owner lookup failed for thread %s", thread_id, exc_info=True)
        return None
